# Herokuデプロイ用のDockerfile
FROM golang:alpine as builder

RUN apk update \
    && apk add --no-cache git curl \
    && go get github.com/oxequa/realize

WORKDIR /go/src/api

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN mkdir -p /build/web

RUN GOOS=linux GOARCH=amd64 go build -o=/build/server web/server.go

FROM alpine:3.9

COPY --from=builder /build /build
RUN chmod u+x /build/server

ENV PORT=${PORT}

WORKDIR /build
ENTRYPOINT ["./server"]